### ISSUE TITLE
CLI interface for suspect/resume window

### ISSUE THREAD

**Issue by jonasfj** [octarinedev/cluster#4]
Command line interface for suspend/resume could be cool..

Is there any?

**Comment by octarinedev** [comment]
@jonasfj there has been some ideas around that since the beginning of this project. Unfortunately there are limitations both in terms of development and work for the user at this stage.

**Comment by jonasfj** [comment]
Fair enough, thanks for the answer...

**Comment by octarinedev** [comment]
No worries thank you for the feedback.
